### ISSUE TITLE
API

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-confidential#2]
Panda Confidential is a synthesis of AWS KMS with TweetNaCl. KMS provides randomness, key management, and key encryption.  TweetNaCl provides expert-curated, auditable implementation of core cryptographic operations:

- Symmetric encryption
- Symmetric public-key encryption
- Asymmetric public-key encryption
- Asymmetric public-key signing

These terms aren't particularly helpful. They correspond to scenarios:

- Alice wants to encrypt something so only she can decrypt it.
- Alice wants to encrypt something that only Bob can decrypt.
- Alice wants to encrypt something that she or Bob can decrypt.
- Alice wants to sign something.

We can break these into three encryption scenarios and one signing scenario. Let's focus on the encryption scenarios.

We can differentiate these three scenarios in a variety of ways. But perhaps the most compelling is by key types. We have three kinds of private keys:

- A private key
- A private key in a key pair
- A shared key derived from a keypair

Thanks to KMS, we never need to think about the first case. For the second and third types of keys, we can define corresponding types: _PublicKey_, _PrivateKey_,  and _SharedKey_. Each type can have corresponding type predicates. We can then implement each scenario based on the type.

##### Alice wants to encrypt something so only she can decrypt it.

_encrypt plainText  &rarr; cipherText_

_decrypt cipherText  &rarr; plainText_

##### Alice wants to encrypt something that only Bob can decrypt.

_encrypt publicKey, plainText  &rarr; cipherText_

_decrypt privateKey, cipherText  &rarr; plainText_

##### Alice wants to encrypt something that she or Bob can decrypt.

_encrypt sharedKey, plainText  &rarr; cipherText_

_decrypt sharedKey, cipherText  &rarr; plainText_

In addition, our key types can provide helpers. For example, we can construct a shared key by providing a key pair, and let the constructor create the shared key for us. A key pair type can provide a constructor and attributes for the private and public key, wrapped as instances of the given types.

That leaves us with _sign_:

_sign privateKey, plainText &rarr; signedText_

Simple enough. But given a signed message, however, we need to be able to verify the signature. This is tricky because we also want to be able to read the message without a tedious conditional: _if isSignedBy …_

We can treat this operation as a form of assertion. (Conceptually speaking, not in the sense of throwing if it fails.)

_attest publicKey, signedText &rarr; plainText_

If we further make these four methods curryable, we can effectively create “stamps” for signing. The only problem here is that we have a variant of _encrypt/decrypt_ that takes only one argument. However, we can expressly define single argument variants that return functions instead of using `curry`.

For example, we can create a encrypted and signed message factory like this:

```
factory = ({from, to}) ->
  _encrypt = encrypt to
  _sign = sign from
  (content) -> _encrypt _sign content

message = factory from: alice, to: bob

# produces a message only Bob can read, signed by Alice
message "Bob, this is Alice. I know about Mallory."
```

We can similarly create a factory for reading messages.

**Comment by dyoder** [comment]
We can create the types using classes:

```coffee
class Key
  @create: (key) -> new @ key
  constructor: (@key) ->
  @p: (instance) -> isType @, instance

class PublicKey extends Key
class PrivateKey extends Key
class SharedKey extends Key
  @create: (description) -> new @ description
  constructor: ({public, private}) ->
     # construct shared key
```

**Comment by cardoni** [comment]
This is great learning.  Had never heard of `TweetNaCl` prior!
